GET {{Catprinter_Web_App.Server_HostAddress}}/search/
Accept: application/json

###

POST {{Catprinter_Web_App.Server_HostAddress}}/connect/
Content-Type: text/plain
Accept: application/json

###

POST {{Catprinter_Web_App.Server_HostAddress}}/process/
Content-Type: application/json
Accept: application/json

###

POST {{Catprinter_Web_App.Server_HostAddress}}/print/
Content-Type: application/json
Accept: application/json

###

